
stages:
  - build
  - test
  - delivery

variables:
  IMAGE_NAME: $CI_REGISTRY_IMAGE:$CI_BUILD_REF_NAME

build:
  image: docker:latest 
  services:
    - docker:dind
  stage: build
  script:
      - docker login -u "gitlab-ci-token" -p "$CI_JOB_TOKEN" $CI_REGISTRY
      - docker buildx build --platform linux/arm,linux/arm64,linux/amd64 -t $IMAGE_NAME .
  tags:
    - docker


test:
  image: $IMAGE_NAME
  stage: test
  script:
      - python -m doctest -v test/test_with_doctest.py 
  tags:
    - docker  

delivery:
  image: docker
  stage: delivery
  services:
     - name: docker:dind
  script:
    - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD 
    - docker buildx build --platform linux/arm,linux/arm64,linux/amd64 -t $CI_REGISTRY_IMAGE . #--platform linux/arm32v7
    - docker push $CI_REGISTRY_IMAGE

