name: Pipeline CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: [self-hosted, linux, ARM64]
    container: 
      image: arm64v8/python
      env:
        NODE_ENV: arduinoEnv


    # defaults:
    #   run:
    #     working-directory: app
    #     shell: bash
    
    # env:
    #    RUNNER_ARCH : ARM


    steps:

    # - name: check out code
    #   uses: actions/checkout@v2

    # - name: Build Docker Image
    #   uses: docker/build-push-action@v1
    #   with:
    #     repository: my-example-image
    #     tags: latest
    # - uses: boostchicken-dev/actions-docker-extract@v2
    #   id: extract
    #   with:
    #     image: my-example-image
    #     path: /app/.
    # - name: Upload Dist
    #   uses: actions/upload-artifact@v2
    #   with:
    #     path: ${{ steps.extract.outputs.destination }}
    #     name: dist



    - name: Login to Docker Hub
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - uses: docker/build-push-action@v2
    - name: Build the Docker image
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        docker image build -t bhpdocker/terrarium_target:latest .
#   


    # - name: Setup Python
    #   uses: actions/setup-python@v4.2.0
    #   with:
    #     # Version range or exact version of Python or PyPy to use, using SemVer's version range syntax. Reads from .python-version if unset.
    #     python-version: # optional
    #       arm32v7/python:3
      
    #     cache: # optional
    #       x86

    #     architecture: # optional
    #       linux/arm32v7
        

    # - name: Build and push
    #   if: github.event_name == 'pull_request'
    #   id: docker_build
    #   uses: docker/build-push-action@v2
    #   with:
    #     context: ./app
    #     file: ./app/Dockerfile
    #     push: true
    #     tags: ${{ secrets.DOCKER_USERNAME }}/app:${{ steps.buildnumber.outputs.build_number }}


  test:
    runs-on: [self-hosted, linux, ARM64]
    needs: [build]
    container: 
      image: bhpdocker/terrarium_target:latest
      # env:
      #   NODE_ENV: arduinoEnv

    # defaults:
    #   run:
    #     working-directory: app
    #     shell: bash
    
    # env:
    #     RUNNER_ARCH : ARM





    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py')
    - name: Analysing the code with doctest
      run: |
        - python -m doctest -v test/test_with_doctest.py 



  delivery:

    runs-on: [self-hosted, linux, ARM64]
     #[self-hosted, linux, ARM]
    needs: [test]
    container: 
       image: bhpdocker/terrarium_target:latest
    #   env:
    #     NODE_ENV: arduinoEnv

    # defaults:
    #   run:
    #     working-directory: app
    #     shell: bash
    
    # env:
    #     RUNNER_ARCH : ARM



    steps:
    # - uses: actions/checkout@v3
    # - name: Set up Python
    #   uses: actions/setup-python@v3
    #   with:
    #     python-version: '3.x'
    # - name: Install dependencies
    #   run: |
    #     python -m pip install --upgrade pip
    #     pip install build
    - name: Build package
      run: python -m build
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}




















# stages:
#   - build
#   - test
#   - delivery

# variables:
#   IMAGE_NAME: $CI_REGISTRY_IMAGE:$CI_BUILD_REF_NAME

# build:
#   image: docker:latest 
#   services:
#     - docker:dind
#   stage: build

#   script:
#       - docker login -u "gitlab-ci-token" -p "$CI_JOB_TOKEN" $CI_REGISTRY
#       - docker buildx build --platform linux/arm,linux/arm64,linux/amd64 -t $IMAGE_NAME .
#   tags:
#     - docker


# test:
#   image: $IMAGE_NAME
#   stage: test
#   script:
#       - python -m doctest -v test/test_with_doctest.py 
#   tags:
#     - docker  

# delivery:
#   image: docker
#   stage: delivery
#   services:
#      - name: docker:dind
#   script:
#     - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD 
#     - docker buildx build --platform linux/arm,linux/arm64,linux/amd64 -t $CI_REGISTRY_IMAGE . #--platform linux/arm32v7
#     - docker push $CI_REGISTRY_IMAGE

