name: Pipeline CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  build_test_delivery:

    runs-on: ubuntu-20.04
    env:      
    #   DOCKER_REGISTRY: brunohenriquep180@gmail.com      
      DOCKER_IMAGE: bhpdocker/terrarium_target      
    #   DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
    #   DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}  
    #   DOCKER_TARGET_PLATFORM: linux/arm/v8
    # container: 
    #   image: arm64v8/python
  

    steps:

    # Get the repository's code
    - name: Checkout
      uses: actions/checkout@v2
      # https://github.com/docker/setup-qemu-action
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
      # https://github.com/docker/setup-buildx-action
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: login to docker hub
      run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: build the image
      run: |
        docker buildx build \
          --tag ${{ env.DOCKER_IMAGE }} \
          --platform linux/arm64  .


    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
  
    # - name: Analysing the code with pylint
    #   run: |
    #     pylint $(git ls-files '*.py')
    - name: Analysing the code with doctest
      run: |
        python -m doctest -v test/test_with_doctest.py 


    - name: Push to Docker Hub
      uses: docker/build-push-action@v2
      with:
        context: .
        platforms: linux/arm64
        push: true
        tags: bhpdocker/terrarium_target:latest #, bhpdocker/terrarium_target:${{ github.run_number }}
    







  # test:
  #   runs-on: ubuntu-20.04

  #   needs: [build]


  #   steps:
      
  #   - name: Checkout
  #     uses: actions/checkout@v2
  #       # https://github.com/docker/setup-qemu-action
  #   - name: Set up QEMU
  #     uses: docker/setup-qemu-action@v1


    # delivery:

  #   runs-on: ubuntu-18.04
  #   needs: [test]
  #   container: 
  #      image: bhpdocker/terrarium_target:latest
  #   # 
  #   # defaults:
  #   #   run:
  #   #     working-directory: app
  #   #     shell: bash
    













    #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


  #   strategy:
  #     matrix:
  #       python-version: ["3.8", "3.9", "3.10"]
  