name: Pipeline CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  build:

    runs-on: ubuntu-20.04
    env:           
      DOCKER_IMAGE: bhpdocker/terrarium_target 
  

    steps:

    # Get the repository's code
    - name: Checkout
      uses: actions/checkout@v2
      # https://github.com/docker/setup-qemu-action
      
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
      # https://github.com/docker/setup-buildx-action
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: build the image
      run: |
        docker buildx build \
          --tag ${{ env.DOCKER_IMAGE }} \
          --platform linux/arm64  .



  test:

    runs-on: ubuntu-20.04
    needs: [build]

    steps:
    # Get the repository's code
    - name: Checkout
      uses: actions/checkout@v2
      # https://github.com/docker/setup-qemu-action
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
      # https://github.com/docker/setup-buildx-action
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    # - name: Install dependencies
    #   run: |
    #     python -m pip install --upgrade pip
    #     pip install pylint
  
    # - name: Analyze code with pylint
    #   run: |
    #     pylint $(git ls-files '*.py')
    - name: Analyze code with doctest
      run: |
        python -m doctest -v test/test_with_doctest.py 


  delivery:

    runs-on: ubuntu-20.04
    needs: [test]

    env:           
      DOCKER_IMAGE: env.DOCKER_IMAGE
  

    steps:
    # Get the repository's code
    - name: Checkout
      uses: actions/checkout@v2
      # https://github.com/docker/setup-qemu-action
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
      # https://github.com/docker/setup-buildx-action
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: login to docker hub
      run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Push to Docker Hub
      uses: docker/build-push-action@v2
      with:
        context: .
        platforms: linux/arm64
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/terrarium_target:latest 
        cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/terrarium_target:buildcache
        cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/terrarium_target:buildcache,mode=max
